project:
  type: website

website:
  title: "Blog"
  navbar:
    pinned: false
    right:
      - text: Home
        href: index.qmd
      - text: About
        href: about/about.qmd
      - icon: github
        href: https://github.com/fanhenrique/blog

format:
  html:
    theme: theme.scss
    template-partials: template-partials/title-block.html
    page-layout: article
    link-external-icon: true
    link-external-filter: ^(?:http:|https:)\/\/fanhenrique\.github\.io\/blog\/

lang: pt-BR
date-format: medium
strip-comments: true