name: Publish

on:
  push:
    branches: main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with: 
          version: 1.6.32
      
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
            name: build
            path: ./_site


  deploy:
      runs-on: ubuntu-latest
      needs: build
      if: github.ref == 'refs/heads/main'        
      permissions:
          contents: write

      steps: 
        - name: Download build artifacts
          uses: actions/download-artifact@v4
          with:
            name: build
            path: ./_site

        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v4
          with:
            deploy_key: ${{ secrets.DEPLOY_GH_PAGES }}
            publish_dir: ./_site
